-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.areas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT areas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  user_email text,
  user_role USER-DEFINED,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  area_id uuid,
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  address text,
  manager_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id),
  CONSTRAINT branches_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.business_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  evaluated_by uuid NOT NULL,
  photo_urls ARRAY,
  business_viability_score integer CHECK (business_viability_score >= 1 AND business_viability_score <= 10),
  repayment_capacity_score integer CHECK (repayment_capacity_score >= 1 AND repayment_capacity_score <= 10),
  character_score integer CHECK (character_score >= 1 AND character_score <= 10),
  overall_score integer CHECK (overall_score >= 1 AND overall_score <= 10),
  notes text,
  risk_assessment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT business_evaluations_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT business_evaluations_evaluated_by_fkey FOREIGN KEY (evaluated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.capital_buildup (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL UNIQUE,
  total_balance numeric DEFAULT 0,
  last_deposit_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT capital_buildup_pkey PRIMARY KEY (id)
);
CREATE TABLE public.centers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  leader_id uuid,
  field_officer_id uuid,
  meeting_location text NOT NULL,
  meeting_day text NOT NULL,
  meeting_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT centers_pkey PRIMARY KEY (id),
  CONSTRAINT centers_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT centers_field_officer_id_fkey FOREIGN KEY (field_officer_id) REFERENCES public.profiles(id),
  CONSTRAINT centers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_centers_leader FOREIGN KEY (leader_id) REFERENCES public.members(id)
);
CREATE TABLE public.global_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT global_settings_pkey PRIMARY KEY (id),
  CONSTRAINT global_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.loan_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  approver_role USER-DEFINED NOT NULL,
  action USER-DEFINED NOT NULL,
  comments text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loan_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT loan_approvals_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT loan_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  center_id uuid NOT NULL,
  loan_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::loan_status,
  principal_amount numeric NOT NULL CHECK (principal_amount > 0::numeric),
  interest_rate numeric NOT NULL DEFAULT 2.00,
  term_weeks integer NOT NULL CHECK (term_weeks > 0),
  purpose text NOT NULL,
  total_interest numeric NOT NULL,
  cbu_amount numeric NOT NULL,
  total_amount numeric NOT NULL,
  weekly_payment numeric NOT NULL,
  outstanding_balance numeric NOT NULL,
  total_paid numeric DEFAULT 0,
  disbursement_date date,
  disbursement_method text,
  disbursed_by uuid,
  last_payment_date date,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loans_pkey PRIMARY KEY (id),
  CONSTRAINT loans_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT loans_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id),
  CONSTRAINT loans_disbursed_by_fkey FOREIGN KEY (disbursed_by) REFERENCES public.profiles(id),
  CONSTRAINT loans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.member_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['proof_of_billing'::text, 'valid_id'::text, 'business_permit'::text, 'barangay_clearance'::text, 'other'::text])),
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_documents_pkey PRIMARY KEY (id),
  CONSTRAINT member_documents_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT member_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT member_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  center_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  date_of_birth date NOT NULL,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  phone text,
  address text NOT NULL,
  business_name text,
  business_type text,
  business_address text,
  cbu_balance numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  joined_date date DEFAULT CURRENT_DATE,
  spouse_name text,
  beneficiary_name text,
  beneficiary_relationship text,
  beneficiary_phone text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT members_pkey PRIMARY KEY (id),
  CONSTRAINT members_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role USER-DEFINED NOT NULL,
  resource USER-DEFINED NOT NULL,
  action USER-DEFINED NOT NULL,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'field_officer'::user_role,
  area_id uuid,
  branch_id uuid,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_profiles_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.repayment_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  week_number integer NOT NULL,
  due_date date NOT NULL,
  principal_due numeric NOT NULL,
  interest_due numeric NOT NULL,
  total_due numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  payment_date date,
  is_paid boolean DEFAULT false,
  days_overdue integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT repayment_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT repayment_schedules_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid,
  member_id uuid NOT NULL,
  center_id uuid NOT NULL,
  collection_sheet_id uuid,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  loan_payment numeric NOT NULL DEFAULT 0,
  cbu_payment numeric NOT NULL DEFAULT 0,
  insurance_payment numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL,
  collected_by uuid NOT NULL,
  receipt_number text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT transactions_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT transactions_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id),
  CONSTRAINT transactions_collection_sheet_id_fkey FOREIGN KEY (collection_sheet_id) REFERENCES public.weekly_collection_sheets(id),
  CONSTRAINT transactions_collected_by_fkey FOREIGN KEY (collected_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.weekly_collection_sheets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  center_id uuid NOT NULL,
  collection_date date NOT NULL,
  field_officer_id uuid,
  status USER-DEFINED DEFAULT 'pending'::collection_status,
  total_collected numeric DEFAULT 0,
  verified_by uuid,
  verified_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_collection_sheets_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_collection_sheets_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id),
  CONSTRAINT weekly_collection_sheets_field_officer_id_fkey FOREIGN KEY (field_officer_id) REFERENCES public.profiles(id),
  CONSTRAINT weekly_collection_sheets_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);