export const PROVINCES = [
  'Metro Manila',
  'Abra',
  'Agusan del Norte',
  'Agusan del Sur',
  'Aklan',
  'Albay',
  'Antique',
  'Apayao',
  'Aurora',
  'Basilan',
  'Bataan',
  'Batanes',
  'Batangas',
  'Benguet',
  'Biliran',
  'Bohol',
  'Bukidnon',
  'Bulacan',
  'Cagayan',
  'Camarines Norte',
  'Camarines Sur',
  'Camiguin',
  'Capiz',
  'Catanduanes',
  'Cavite',
  'Cebu',
  'Cotabato',
  'Davao de Oro',
  'Davao del Norte',
  'Davao del Sur',
  'Davao Occidental',
  'Davao Oriental',
  'Dinagat Islands',
  'Eastern Samar',
  'Guimaras',
  'Ifugao',
  'Ilocos Norte',
  'Ilocos Sur',
  'Iloilo',
  'Isabela',
  'Kalinga',
  'La Union',
  'Laguna',
  'Lanao del Norte',
  'Lanao del Sur',
  'Leyte',
  'Maguindanao',
  'Marinduque',
  'Masbate',
  'Misamis Occidental',
  'Misamis Oriental',
  'Mountain Province',
  'Negros Occidental',
  'Negros Oriental',
  'Northern Samar',
  'Nueva Ecija',
  'Nueva Vizcaya',
  'Occidental Mindoro',
  'Oriental Mindoro',
  'Palawan',
  'Pampanga',
  'Pangasinan',
  'Quezon',
  'Quirino',
  'Rizal',
  'Romblon',
  'Samar',
  'Sarangani',
  'Siquijor',
  'Sorsogon',
  'South Cotabato',
  'Southern Leyte',
  'Sultan Kudarat',
  'Sulu',
  'Surigao del Norte',
  'Surigao del Sur',
  'Tarlac',
  'Tawi-Tawi',
  'Zambales',
  'Zamboanga del Norte',
  'Zamboanga del Sur',
  'Zamboanga Sibugay',
]

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Metro Manila': [
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  'Cebu': [
    'Cebu City',
    'Mandaue',
    'Lapu-Lapu',
    'Talisay',
    'Toledo',
    'Danao',
    'Carcar',
    'Naga',
    'Bogo',
  ],
  'Davao del Sur': [
    'Davao City',
    'Digos',
  ],
  'Laguna': [
    'Calamba',
    'Santa Rosa',
    'Biñan',
    'San Pedro',
    'Cabuyao',
    'San Pablo',
  ],
  'Cavite': [
    'Bacoor',
    'Dasmariñas',
    'Imus',
    'Cavite City',
    'Tagaytay',
    'Trece Martires',
    'General Trias',
  ],
  'Bulacan': [
    'Malolos',
    'Meycauayan',
    'San Jose del Monte',
  ],
  'Pampanga': [
    'Angeles',
    'San Fernando',
    'Mabalacat',
  ],
  'Batangas': [
    'Batangas City',
    'Lipa',
    'Tanauan',
  ],
  'Rizal': [
    'Antipolo',
  ],
  'Pangasinan': [
    'Dagupan',
    'San Carlos',
    'Urdaneta',
    'Alaminos',
  ],
  'Iloilo': [
    'Iloilo City',
    'Passi',
  ],
  'Negros Occidental': [
    'Bacolod',
    'Bago',
    'Cadiz',
    'Escalante',
    'Himamaylan',
    'Kabankalan',
    'La Carlota',
    'Sagay',
    'San Carlos',
    'Silay',
    'Sipalay',
    'Talisay',
    'Victorias',
  ],
}

export const ID_TYPES = [
  { value: 'national_id', label: 'National ID (PhilSys)' },
  { value: 'drivers_license', label: "Driver's License" },
  { value: 'passport', label: 'Passport' },
  { value: 'umid', label: 'UMID' },
  { value: 'philhealth', label: 'PhilHealth ID' },
]

export const BUSINESS_TYPES = [
  'Sari-sari Store',
  'Food Vendor',
  'Online Seller',
  'Small Retail',
  'Carinderia',
  'Bakery',
  'Laundry Shop',
  'Beauty Salon',
  'Barbershop',
  'Tailoring',
  'Repair Shop',
  'Transportation',
  'Agriculture',
  'Livestock',
  'Fishing',
  'Construction',
  'Services',
  'Other',
]

export const REGISTRATION_TYPES = [
  { value: 'dti', label: 'DTI Registration' },
  { value: 'barangay_permit', label: 'Barangay Permit' },
  { value: 'sec', label: 'SEC Registration' },
  { value: 'none', label: 'None' },
]

export const CIVIL_STATUS_OPTIONS = [
  { value: 'single', label: 'Single' },
  { value: 'married', label: 'Married' },
  { value: 'widowed', label: 'Widowed' },
  { value: 'separated', label: 'Separated' },
  { value: 'divorced', label: 'Divorced' },
]

export const GENDER_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Prefer not to say' },
]

export const HOUSING_TYPE_OPTIONS = [
  { value: 'owned', label: 'Owned' },
  { value: 'renting', label: 'Renting' },
  { value: 'living_with_family', label: 'Living with Family' },
]
